[toolchain]


[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "5NjgwpGKcNsR5TNWSmCFTjR4PZ6kjZ4YqncqYJZccxFk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # [localnet, testnet, mainnet, devnet]
wallet = "/Users/ted/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
